/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atvassociacao;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author joaop
 */
public class AssoGrafico extends javax.swing.JFrame {
   
            
    ArrayList<String> produtos = new ArrayList();
    ArrayList<String> precoProdutos = new ArrayList();
    int valor, i, id;
    double comissao;   
    public Vendedor vendedor;
    
    
    
    public AssoGrafico() {
        initComponents();
        butaoFinalizar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxVendedor = new javax.swing.JComboBox<>();
        TextVendedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxProduto = new javax.swing.JComboBox<>();
        botaoAdd = new javax.swing.JButton();
        butaoFinalizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Textpreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextNcasa = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Casa do eletrodomestico");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vendedor (Cód)");

        boxVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "11" }));
        boxVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxVendedorActionPerformed(evt);
            }
        });

        TextVendedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Digite o nome do Cliente");

        TextCliente.setBackground(new java.awt.Color(255, 255, 255));
        TextCliente.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Produto");

        BoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione>>", "liquidificador", "batedeira", "sanduicheira", "cafeteira", "geladeira" }));
        BoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxProdutoActionPerformed(evt);
            }
        });

        botaoAdd.setBackground(new java.awt.Color(255, 34, 34));
        botaoAdd.setFont(new java.awt.Font("DejaVu Sans Light", 1, 14)); // NOI18N
        botaoAdd.setForeground(new java.awt.Color(0, 0, 0));
        botaoAdd.setText("Adicionar");
        botaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddActionPerformed(evt);
            }
        });

        butaoFinalizar.setBackground(new java.awt.Color(51, 255, 51));
        butaoFinalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        butaoFinalizar.setText("Finalizar Pedido");
        butaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoFinalizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Valor");

        Textpreco.setBackground(new java.awt.Color(255, 255, 255));
        Textpreco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Textpreco.setForeground(new java.awt.Color(0, 0, 0));
        Textpreco.setCaretColor(new java.awt.Color(255, 255, 255));
        Textpreco.setEnabled(false);
        Textpreco.setSelectionColor(new java.awt.Color(0, 0, 0));
        Textpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextprecoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("R$");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Endereço do Cliente");

        TextEndereco.setBackground(new java.awt.Color(255, 255, 255));
        TextEndereco.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        jLabel7.setText("Nº Casa");

        TextNcasa.setBackground(new java.awt.Color(255, 255, 255));
        TextNcasa.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TextEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextVendedor)
                                .addComponent(TextCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextNcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Textpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(butaoFinalizar)
                        .addGap(201, 201, 201))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Textpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextNcasa)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(butaoFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddActionPerformed
    
    if(id == 0){
        JOptionPane.showMessageDialog(null,"Selecione um ID válido","Atenção",JOptionPane.ERROR_MESSAGE);
    }
    
    if(BoxProduto.getSelectedItem() == "selecione>>"){
        JOptionPane.showMessageDialog(null,"Selecione uma opção!","Erro",
                JOptionPane.ERROR_MESSAGE);
    }
    else{
        
        produtos.add(BoxProduto.getSelectedItem().toString());
        precoProdutos.add(Textpreco.getText());
        valor = Integer.parseInt(Textpreco.getText());
        i += valor;
        butaoFinalizar.setVisible(true); 
    }  
    
    }//GEN-LAST:event_botaoAddActionPerformed

    private void boxVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxVendedorActionPerformed
    id = boxVendedor.getSelectedIndex();
     
    if(id == 1){
        TextVendedor.setText("João Pedro");
     }
    if(id == 2){
        TextVendedor.setText("Kelly"); 
    }
    if(id == 0){
        JOptionPane.showMessageDialog(null,"Selecione um ID válido","Atenção",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_boxVendedorActionPerformed

    private void BoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxProdutoActionPerformed
        int item = BoxProduto.getSelectedIndex();
       
        if(item == 0){
        JOptionPane.showMessageDialog(null,"Selecione um produto válido","Atenção",JOptionPane.ERROR_MESSAGE);
        }
        
        if(item == 1){
            Textpreco.setText("40"); 
        }
        if(item == 2){
            Textpreco.setText("45"); 
        }
        if(item == 3){
            Textpreco.setText("35");
        }
        if(item == 4){
            Textpreco.setText("60"); 
        }
        if(item == 5){
            Textpreco.setText("1060"); 
        }
    }//GEN-LAST:event_BoxProdutoActionPerformed

    private void TextprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextprecoActionPerformed

    private void butaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoFinalizarActionPerformed
    
        if(!"".equals(TextCliente.getText())
                && !"".equals(TextEndereco.getText())
                && !"".equals(TextNcasa.getText())){
            comissao = i*0.2;
            
            JOptionPane.showMessageDialog(this,"Vendedor: "+TextVendedor.getText()
                  +"\nCliente: "+TextCliente.getText()+"\nProduto(s): "
                  +new ArrayList(produtos)+"\nValor total: R$"+ i
                  +"\nComissão do vendedor: R$"+comissao);
        }
        else{
           JOptionPane.showMessageDialog(this,"Digite todos os dados do cliente!",
                   "Atenção",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_butaoFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssoGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxProduto;
    private javax.swing.JTextField TextCliente;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextNcasa;
    private javax.swing.JTextField TextVendedor;
    private javax.swing.JTextField Textpreco;
    private javax.swing.JButton botaoAdd;
    private javax.swing.JComboBox<String> boxVendedor;
    private javax.swing.JButton butaoFinalizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
